fix: add DEV_APP_NAME check in deployment workflows to abort if not set

diff --git a/workflow-templates/development-deploy.yml b/workflow-templates/development-deploy.yml
--- a/workflow-templates/development-deploy.yml
+++ b/workflow-templates/development-deploy.yml
@@ -5,13 +5,19 @@ on:
 
 env:
   PHP_VERSION: 8.5
+  DEV_APP_NAME: ${{ secrets.DEV_APP_NAME }}
   APP_NAMESPACE: ${{ secrets.DEV_APP_NAME }}
   REMOTE_BASE_PATH: /data/projects/${{ secrets.DEV_APP_NAME }}/
 jobs:
   deploy:
     runs-on: ubuntu-latest
-    if: ${{ secrets.DEV_APP_NAME != '' }}
     steps:
+      - name: Check DEV_APP_NAME
+        if: ${{ env.DEV_APP_NAME == '' }}
+        run: |
+          echo "DEV_APP_NAME secret is not set. Aborting workflow."
+          exit 1
+
       - name: 📄 Clone repository
         uses: actions/checkout@v3
 
